### 异常处理
- 程序中导致程序中断运行的一种指令流
  ``` java
  try {
      // 可能出现异常的语句
  } catch(异常类型1 对象名1) {
      // 处理对象的方法
  } catch(异常类型2 对象名2) {
      // 处理对象的方法
  } finnaly{
      // 异常的统一出口
  }
  ```
- 不管是是否产生异常，最后都会执行finally语句
- 异常发生的过程
  1. 发生了异常（jvm根据异常的情况，创建了一个异常对象-包含了异常信息）
  2. main未处理，自动将异常抛给了main的调用者JVM
  3. JVM对异常信息进行了响应（将异常信息显示到控制台，中断处理）
- 异常体系结构
  - 受检异常
  - 非受检异常
****
******
*****
***
- throws
  - 方法声明上使用，表示方法中不处理异常，而交给调用处处理
- throw
  - 程序中人为的抛出一个异常
- 常见面试题目
  1.  try-catch-finally 中哪个部分可以省略?
答: catch和finally可以省略其中一个 ， catch和finally不能同时省略
注意:格式上允许省略catch块, 但是发生异常时就不会捕获异常了,我们在开发中也不会这样去写代码.
  2. try-catch-finally 中，如果 catch 中 return 了，finally 还会执行吗? 答:finally中的代码会执行
详解:
执行流程:
     1. 先计算返回值， 并将返回值存储起来， 等待返回 2. 执行finally代码块
     2. 将之前存储的返回值， 返回出去;
     需注意:
     1. 返回值是在finally运算之前就确定了，并且缓存了，不管finally对该值做任何的改变，返回的值都不
     会改变
     1. finally代码中不建议包含return，因为程序会在上述的流程中提前退出，也就是说返回的值不是try或
     catch中的值
     1. 如果在try或catch中停止了JVM,则finally不会执行.例如停电- -, 或通过如下代码退出
     JVM:System.exit(0);  

finally:只有电脑内存停了，关机了，finally不会执行
finally return 两种情况
finally 必然执行，除非在catch里面有system.exit(status:0)
异常是否抛出去：传参数错误导致的
运行异常不会出现红线

统一使用nextLine，如果一开始使用nextIntnextL接着用nextLine的话，在敲回车的时候，该值就被赋给了nextLine。



### 错误
equals比较的时候，报错，因为null问题,equals前面应该是非空。
“退出” 可以用 return.
try捕捉异常的方法
代码结构设计，分成小块 MVC
在一个类的两个方法里面可以两次新建 new Express（）？